# v2 syntax
version: '2'

services:
  # PHP (with nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: pokemon-consume-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
